base_locale: en
locales: [en, ca, ca]

data:
  external:
    - "<%= %x[bundle info decidim-core --path].chomp %>/config/locales/%{locale}.yml"
    - "<%= %x[bundle info decidim-verifications --path].chomp %>/config/locales/%{locale}.yml"

